<a href="https://colab.research.google.com/github/harry9855/PYTHON-AI-ML/blob/main/PandasMultIndexSeriesDf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MULTI INDEX SERIES & DATAFRAME

In [ ]:
import numpy as np
import pandas as pd

## CREATING MULIT INDEX SERIES

In [ ]:
index_val = [
    ('cse', 2019),
    ('cse', 2020),
    ('cse', 2021),
    ('cse', 2022),
    ('ece', 2019),
    ('ece', 2020),
    ('ece', 2021),
    ('ece', 2022)
]

a = pd.Series(
    [1,2,3,4,6,7,8,9],
    index=index_val
)
a

# It is not correct way of creating multi index series , because creating this type of multi index
# may cause difficulty when we need call all data of cse , because now we have to call full group one by one

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    6
(ece, 2020)    7
(ece, 2021)    8
(ece, 2022)    9
dtype: int64

So Now To create a Multi index series , we need to create a multi index object

And Multi Index series is same as heirarchial Indexing ( because it create hiearchy in indexes)

In [ ]:
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex
# it is a multi index object , which treat stream and year as two different values not same

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [ ]:
# of we want to check then
multiindex.levels

# here we can see cse and ece as two different index and years as different index ( it has decoupled from tuple)

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [ ]:
# Multi Index product
# it is a function that is used to create multi index series , and helps again rewriting indexes
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

# it does cartiesian product between two list which have passed

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [ ]:
s=pd.Series([1,2,3,4,5,6,7,8],index=multiindex)

In [ ]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [ ]:
# We can also Convert Multi Index Series to Data Frame
# beacause multi index series is a 2D series
temp=s.unstack()

In [ ]:
# If we 2D or more x-D data frame then we can convert it to multi index series
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

WHY THERE IS NEED OF MULTI INDEX SERIES ?

---
By Using Multi indexing we expressed higher dimension in lower dimension 'Object'

## MULTI INDEX DATA FRAME

In [ ]:
branch_df1=pd.DataFrame(
    [[1,2],
     [3,4],
     [5,6],
     [7,8],
     [9,10],
     [11,12],
     [13,14],
     [15,16]] , index=multiindex , columns=['average_pkg','students']
    )

In [ ]:
branch_df1

          average_pkg  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [ ]:
# Now if we want to fetch any data
branch_df1.loc['cse'] # this will fetch all data from cse

      average_pkg  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [ ]:
branch_df1['average_pkg']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: average_pkg, dtype: int64

In [ ]:
# We can Apply multi index on both row and column
branch_df2=pd.DataFrame(
    [[1,2,0,0],
     [3,4,0,0],
     [5,6,0,0],
     [7,8,0,0],], index=[2019,2020,2021,2022] , columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_pkg','students']])
    )

In [ ]:
branch_df2

           delhi               mumbai
     average_pkg students average_pkg students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [ ]:
branch_df2

           delhi               mumbai
     average_pkg students average_pkg students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [ ]:
branch_df2['mumbai']['average_pkg'] # It shows the average package of the mumbai in different year

2019    0
2020    0
2021    0
2022    0
Name: average_pkg, dtype: int64

In [ ]:
branch_df2.loc[2019]

delhi   average_pkg    1
        students       2
mumbai  average_pkg    0
        students       0
Name: 2019, dtype: int64

In [ ]:
# We can Apply multi index on both row and column
# Here i have applied in both rows and cols
branch_df3=pd.DataFrame(
    [[1,2,0,0],
     [3,4,0,0],
     [5,6,0,0],
     [7,8,0,0],
     [9,10,0,0],
     [11,12,0,0],
     [13,14,0,0],
     [15,16,0,0]] , index=multiindex , columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_pkg','students']])
    )

In [ ]:
branch_df3 # this data is of dimension 4D data

               delhi               mumbai
         average_pkg students average_pkg students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## STACKING AND UNSTACKING

In [ ]:
branch_df1.unstack()

    average_pkg                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [ ]:
# bascially we have two levels of indexing in rows and when we apply
# unstack the 0th level of indexing moves to coloumn

In [ ]:
branch_df1.unstack().unstack()

average_pkg  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [ ]:
# Here we applied two unstack but we also have two levles of indexing both rows index have been
# have been converted to coloumns so there are now rows and our dataframe has been converted to multi index series

In [ ]:
# similarly stacking works but vice versa way
# from columns level 0 col converts to row
branch_df1.unstack().stack()
# one thing to note stack does not works on series

/tmp/ipykernel_1503/134910562.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

          average_pkg  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [ ]:
branch_df1.unstack().stack().stack()
# all cols have removed and converted to rows and now it has become series

/tmp/ipykernel_1503/2266968651.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack().stack()

cse  2019  average_pkg     1
           students        2
     2020  average_pkg     3
           students        4
     2021  average_pkg     5
           students        6
     2022  average_pkg     7
           students        8
ece  2019  average_pkg     9
           students       10
     2020  average_pkg    11
           students       12
     2021  average_pkg    13
           students       14
     2022  average_pkg    15
           students       16
dtype: int64

## EXTRACTING ROWS AND COLS

In [ ]:
branch_df3

               delhi               mumbai
         average_pkg students average_pkg students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [ ]:
#extracting rows
branch_df3.loc[('cse',2021)]

delhi   average_pkg    5
        students       6
mumbai  average_pkg    0
        students       0
Name: (cse, 2021), dtype: int64

In [ ]:
# fetching multiple rows
branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         average_pkg students average_pkg students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [ ]:
# fetching rows using iloc
branch_df3.iloc[0:6:2]

               delhi               mumbai
         average_pkg students average_pkg students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [ ]:
# fetching cols from the table
branch_df3['delhi']

          average_pkg  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [ ]:
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [ ]:
# fetching multiple cols
branch_df3.iloc[:,1:3] # fetching all rows but different cols

            delhi      mumbai
         students average_pkg
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

## SORTING INDEX

In [ ]:
# sorting branch_df3 in descdending order
# sorting will be done on all levels
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         average_pkg students average_pkg students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [ ]:
# but if we want level 0 to be in ascending level 1 to be descending then
branch_df3.sort_index(ascending=[True,False])

               delhi               mumbai
         average_pkg students average_pkg students
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0

In [ ]:
# if we want to sort specific level
branch_df3.sort_index(level=0,ascending=[False])

               delhi               mumbai
         average_pkg students average_pkg students
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0

## TRANSPOSE AND SWAP LEVELS

In [ ]:
# transpose is used to swap cols to rows and rows to cols
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  average_pkg    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai average_pkg    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [ ]:
# Swap level
# if we want to swap levels of rows or cols , we can do it
branch_df3.swaplevel()

               delhi               mumbai
         average_pkg students average_pkg students
2019 cse           1        2           0        0
2020 cse           3        4           0        0
2021 cse           5        6           0        0
2022 cse           7        8           0        0
2019 ece           9       10           0        0
2020 ece          11       12           0        0
2021 ece          13       14           0        0
2022 ece          15       16           0        0

In [ ]:
branch_df3.swaplevel(axis=1) # by chnagig axis we can swap level of cols

         average_pkg students average_pkg students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## LONG VS WIDE DATA

Wide Format : it is where we have a single row for every data point with multiple columns to hold values of various attributes

Long Format : it is where for each data point we have as many rows as the number of attributes and each row contains the value of a particular attribute for given data point